### ISSUE TITLE
Is this demo not finished? I login in and found a good heading and blank main body

### ISSUE THREAD

**Issue by LeoQuote** [Activiti/activiti-cloud-demo-ui#8]
![image](https://user-images.githubusercontent.com/4143818/40726112-9fa16eaa-6457-11e8-8f6c-c5e8495d98c3.png)

**Comment by mteodori** [comment]
this project is deprecated, see ADF for uptodate Angular components to build your Activiti Cloud app from: https://github.com/Alfresco/alfresco-ng2-components
